'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class emailresend
    
    '''<summary>
    '''div_full_holder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents div_full_holder As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''pw_lbl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pw_lbl As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txt_hidden control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_hidden As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''txt_so control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_so As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''status_txt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents status_txt As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''btn_view control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_view As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btn_resend control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_resend As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gv_data control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_data As Global.System.Web.UI.WebControls.GridView
End Class
